# proxypool远程服务器的地址，空白为http://127.0.0.1:8080
server_url: 
#
# - https://free-spy.445600.ga/ 
-  https://hm2019721.ml/ 
-  https://free-spy.445600.ga/ 
-  https://fq.lonxin.net/ 
-  https://free.dswang.ga/ 
-  https://www.233660.xyz/ 
-  https://sspool.nl/ 
- https://sspool.herokuapp.com/ 
- https://proxypool-guest997.herokuapp.com/ 
- https://proxy.purel.in/ 
- https://proxy.51798.xyz/ 
- https://hello.stgod.com/ 
- https://free886.herokuapp.com/ 
- https://free.dswang.ga/ 
- https://fq.lonxin.net/ 
- https://ditan.ml/

#- https://www.yugogogogo.tk/
# - https://www.yugogogogo.tk/clash/proxies
   # - https://www.yugogogogo.tk/clash/proxies?type=ss


# 对于您的本地服务器
request: http   # http / https
domain: 192.168.1.2       # default: 127.0.0.1
port:           # default: 80

cron_interval: 60 # default: 15  minutes
show_remote_speed: true # default false
healthcheck_timeout: 15    # default 5
healthcheck_connection: 100 # default 100
speedtest:   false   # default false
# connection:  5   # default 5
# timout:    15     # default 10
speed_timout:         # default 10
speed_connection:     # default 5
