# proxypool远程服务器的地址，空白为http://127.0.0.1:8080
server_url: 
#
- http://165.232.158.203:90 
#- https://www.yugogogogo.tk/
# - https://www.yugogogogo.tk/clash/proxies
   # - https://www.yugogogogo.tk/clash/proxies?type=ss


# 对于您的本地服务器
request: http   # http / https
domain:        # default: 127.0.0.1
port:   8080        # default: 80

cron_interval: 30 # default: 15  minutes
show_remote_speed: true # default false
healthcheck_timeout: 15    # default 5
healthcheck_connection: 100 # default 100
speedtest:   false   # default false
# connection:  5   # default 5
# timout:    15     # default 10
speed_timeout:         # default 10
speed_connection:     # default 5
